### ISSUE TITLE
Custom header for all events

### ISSUE THREAD

**Issue by veralimita** [GeoffZhu/vue-event-calendar#48]
Can you add please some props to set custom header to list in case of all events? 
Or named slot just like you did for elements.
Thnx.

**Comment by GeoffZhu** [comment]
I try to use named slot, but have some problem. This components have three layers, so slot need transfer, when i use ```<slot name="title" slot="title"></slot>``` to transfer DOM from layer1 to layer3, It's not work well. @veralimita

**Comment by moyvera** [comment]
@GeoffZhu great library !

I'm just starting to use this library and I think a property to modify the header it would be very nice and useful. Not just static, because I think that title depends on what we are loading, for example, from an api endpoint. 

do you think you can change this ?

**Comment by zabaat** [comment]
@GeoffZhu I know this isn't as elegant as you were hoping, but I'm not sure how possible it will be to accomplish what you need.
I think this is a simple work around to the issue for now:
https://github.com/zabaat/vue-event-calendar/commit/869f867cb77a95859145fd829c3eb328cfd27894

Since you expose the day-changed event we can pass custom headers down based on the day at least for now.

**Comment by GeoffZhu** [comment]
Add this feature in 1.5.1.  Thanks @zabaat ., Maybe It's the best choice for now,  at least older versions will not be affected.
